# In the first case x prints 3 with no errors.

# In the second case there is an error because x was initialized in the block, therefore code outside the block can't access it.